title:              KARSTERR Blog
email:              efecan_kara@proton.me
description:        Tech themed blogposts and guides.
author:             Efe Can Kara
baseurl:            "/efecankara_blog.github.io"
url:                "https://karsterr.github.io/efecankara_blog.github.io/"

# Social Profiles
github_username:    KARSTERR
instagram_username:  efecankra
linkedin_username: karsterr

# Build settings
markdown:           kramdown
paginate:           false 
# paginate_path:      "/posts/page:num/" #
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
